---
title: Problem set 3
duedate: October 21st
layout: default
---

First, definitions/reminders that we will use.

Let $$RR$$ be a commutative ring.  A *nonzero* element $$p$$ of the polynomial ring $$R[x]$$ is of the form

$$p=a_nx^n+a_{n-1}x^{n-1}+\cdots+a_0$$ 

with $$a_i\in R$$ and $$a_n\neq 0$$.

The non-negative integer $$n$$ is called the *degree* of $$p$$.  The degree of $$0$$ is conventially set to be $$-\infty$$.

$$a_0$$ is called the *constant term* of $$p$$, $$a_n$$ is called the *leading coefficient* of $$p$$. 

The polynomial $$p$$ is called *monic* if the leading coefficient is one, i.e., if $$a_n=1$$.



Question 1
====
(2 points)


Prove that there is a homomorphism from $$\mathbb{Z}/n\mathbb{Z}$$ to $$\mathbb{Z}/k\mathbb{Z}$$ if and only if $$k$$ divides $$n$$.

Question 2
====
(2 points)

Let $$R$$ be a commutative ring.

1. Let $$N$$ be the union of $$0$$ and all the nilpotent elements of $$R$$.  Prove that $$N$$ is an ideal.  (Hint: the binomial theorem holds for $$R$$)

2. Let $$D$$ be the union of $$0$$ and all the zero divisors of $$R$$.  Give an example to show that $$D$$ need not be an ideal of $$R$$.

Question 3
===
(2 points)

Let $$R=\mathbb{Z}[x]$$.  For each subset of $$R$$, decide, with proof, if it is an ideal of $$R$$

1. Let $$C$$ be the union of $$0$$ and all polynomials $$p$$ with even constant term; i.e., with $$a_0$$ divisible by 2.

2. Let $$L$$ be the unioin of $$0$$ and all polynomials $$p$$ with even leading coefficient; i.e., with $$a_n$$ divisible by 2.

Question 4
====
(4 points)

1.  Let $$f\in \mathbb{Z}[x]$$ be a monic polynomial.  Prove that any polynomial $$p\in \mathbb{Z}[x]$$ may be written as $$p=qf+r$$, where $$q,r\in\mathbb{Z}[x]$$, and the degree of $$r$$ is less than the degree of $$f$$ (Hint: how do you do long division of polynomials?)

2. Let $$\varphi:\mathbb{Z}[x]\to\mathbb{Z}/8\mathbb{Z}$$ be the homomorphism defined by $$\varphi(f)=[f(2)]$$.  So for example, $$\varphi(x^2-3x-1)=[2^2-3\cdot 2-1]=[-3]=[5]$$.  Prove that $$\ker(\varphi)=(8,x-2)$$; that is, the kernel of $$\varphi$$ is the ideal generated by $$8$$ and $$(x-2)$$.  (Hint: part 1 probably helps, otherwise why is this one question?)